[workspace]
resolver = "3"
members = [
    "cpp-hypot-overload",
    "tuple-reflection",
]
default-members = [
    "cpp-hypot-overload",
    "tuple-reflection",
]

[workspace.package]
version = "0.0.0"
authors = [
    "teor <teor@riseup.net",
]
edition = "2024"
homepage = "https://rust-lang.github.io/rust-project-goals/2026/overloading-for-ffi.html"
keywords = [
    "overload",
    "C++",
    "interop",
    "splat",
]
license = "MIT OR APACHE-2.0"
readme = "README.md"
repository = "https://github.com/rustfoundation/overloading-examples"
# Requires #[rustc_splat] which was renamed in nightly-2026-07-31 (rust-lang/rust#159817)
# FIXME: we can't specify nightly dates or the latest nightly here, update to 1.100 once 1.99 beta branches (20 August 2026)
rust-version = "1.99"

[workspace.dependencies]
cpp = "0.5.11"
cpp_build = "0.5.11"
